---
title: "Example Simple-forecasts"
output: html_document
---

```{r}
#Coleta o nome de usuário
user <- Sys.getenv('USERNAME')
user_path <- paste0('C:/Users/', user, '/')

# Define os paths para cada usuário ---------------------------------------

if(user == 'GabrielBelle') {
  #Insira o caminho do arquivo de autentição do series.4macro 
  auth_path <- paste0(user_path, 
                      'Documents/Trabalhos/auth.ini')
  
  git_path <- paste0(user_path,
                     'Documents/Trabalhos/git/')
  
  dre_sharepoint_path <- paste0(user_path,
                                '4intelligence/Feature Store - Documentos/DRE/')
}

library(tidyverse)
library(series.4macro)
library(lubridate)
library(fable)
library(feasts)
library(tsibble)
library(seasonal)
```

```{r}
source_files <- list.files(paste0(git_path,'simple-forecasts/R/'))

for(file_name in source_files){
  source(paste0(git_path,
                'simple-forecasts/R/',
                file_name))
  }
```

### Função para coletar dado da FS
```{r}
sids = c('BREMP0018000OOML', 'BREMP0018000SOML', 'BRGDP0002000ROQL', 'BRGDP0002000WOQL')

load_clean <- load_clean_series(sids, auth_path)

df <- split_series(load_clean, 'BREMP0018000OOML', type = 'realizado')

snaive = snaive(df, drift = F, nmeans = 1, end_projection = "2022-12-01")

holtW = holtWinter(df, type = "multiplicative", end_projection = "2023-12-01")

auto_arima = arimaUnivariate(df, end_projection = "2023-12-01")

pib <- split_series(load_clean, 'BRGDP0002000ROQL', type = 'realizado')
pib_dessaz <- split_series(load_clean, 'BRGDP0002000WOQL', type = 'ambos')

```

### Função para gerar dessaz 
```{r}
pib_dessaz_fct <- get_seas_adj(pib)
```

```{r}
test_dessaz <- pib_dessaz %>%
  rename(dessaz_fs = vl) %>%
  left_join(pib) %>%
  rename(original = vl) %>% 
  left_join(pib_dessaz_fct) %>%
  pivot_longer(-date)
  
ggplot(test_dessaz, aes(x = date, y = value)) +
  geom_line(aes(color = name), size = 1)
```
### Projeção com seas_ratio 

```{r}
seas_ratio_forecast <- seas_ratio(pib, pib_dessaz, nmeans = 5)

tail(seas_ratio_forecast)
```


