---
title: "Example Simple-forecasts"
output: html_document
---

```{r}
rm(list = ls()) # Limpar a memória 

#Coleta o nome de usuário
user <- Sys.getenv('USERNAME')
user_path <- paste0('C:/Users/', user, '/')

# Define os paths para cada usuário ---------------------------------------

if(user == 'GabrielBelle') {
  #Insira o caminho do arquivo de autentição do series.4macro 
  auth_path <- paste0(user_path, 
                      'Documents/Trabalhos/auth.ini')
  
  git_path <- paste0(user_path,
                     'Documents/Trabalhos/git/')
  
  dre_sharepoint_path <- paste0(user_path,
                                '4intelligence/Feature Store - Documentos/DRE/')
}

library(tidyverse)
library(series.4macro)
library(lubridate)
library(fable)
library(feasts)
library(tsibble)
library(seasonal)
library(zoo)
library(tsibbledata)
library(purrr)

set.seed(1)
```

```{r}
source_files <- list.files(paste0(git_path,'simple-forecasts/R/'))

for(file_name in source_files){
  source(paste0(git_path,
                'simple-forecasts/R/',
                file_name))
  }

print(source_files)
```

### Projeções v1

```{r}
lista_4casthub_raw <- readxl::read_xlsx(paste0(
  dre_sharepoint_path,
  'prioritarias/lista_4casthub.xlsx')) %>% 
  suppressWarnings()
```
#### Clima - snaive

```{r}
clima_sid <- lista_4casthub_raw %>% 
  filter(fonte == 'Nasa Power') %>% 
  pluck('serie')
```

```{r}
clima_data <- load_clean_series(clima_sid, auth_path)
```

```{r}
exp_clima <- tibble()
for (sid in sample(clima_sid,6)) {
  print(sid)
  
  sid_data_raw <- split_series(clima_data, sid, 'realizado')
  
  clima_forecast <- snaive(sid_data_raw,
                           nmeans = 5,
                           end_projection = '2026-12-01') %>% 
    mutate(sid = sid)
  
  #Pode mandar pra FS direto
  
  exp_clima <- exp_clima %>% 
    bind_rows(clima_forecast)
}
```

```{r}
ggplot(exp_clima, aes(date, y = vl, color = forecast)) +
  geom_line() +
  facet_wrap(~sid, scale = 'free_y', ncol = 2)
```


#### Mensalização - LatamFocus

```{r}
aux_exp <- function(sid, target, yoy = F) {
  fs_data <- load_clean_series(sid, auth_path) %>% 
    split_series(sid, type = 'realizado')
  
  if(yoy) {
    target <- get_target_from_yoy(fs_data, yoy = target)
  } 
  
  forecast_data <- fs_data %>% 
    get_montly_forecast(end_forecast = '2026-12-01',
                        trend_type = 'linear',
                        target_value = target)
  
  plot_forecast <- ggplot(forecast_data, aes(date, y = vl)) +
    geom_line() +
    annotate("rect",
           xmin = max(fs_data$date),
           xmax = max(forecast_data$date),
           ymin = min(fs_data$vl),
           ymax = Inf,
           alpha = 0.2)
  
  return(list(
    plot_forecast = plot_forecast,
    forecast_data = forecast_data
  ))
}
```


##### Pib Argentina
```{r}
teste <- load_clean_series('ARFXR0041000OEML', auth_path) %>% 
  split_series('ARFXR0041000OEML', type = 'realizado')

```

```{r}
tx_desemp <- load_clean_series(c('CLEMP0087000OOML',
                               'COEMP0090000OOML',                             'PEEMP0089LI3OOML'), auth_path) %>% 
  select(-forecast) %>% 
  mutate(sid = as.character(sid))

c('AREMP0085000OOQL','CLEMP0087000OOML',
                               'COEMP0090000OOML','ECEMP0092000OOQL',
                               'PEEMP0089LI3OOML')

q <- tx_desemp %>% 
  group_by(sid) %>% 
  summarise(max = max(date))
```

```{r}
ggplot(tx_desemp, aes(x = date, y = vl)) +
  geom_line() +
  facet_wrap(~sid, ncol = 1, scale = 'free')
```

#### Top-down 

##### PIM
Extrativa e Transformação

1° passo projetar as aberturas e coletar projeção da série geral
```{r}
pim_sids <- c('BRIND0001000OOML','BRIND0002000OOML','BRIND0003000OOML')

pim_data <- load_clean_series(pim_sids, auth_path)

pim_geral <- split_series(pim_data, 'BRIND0001000OOML', type = 'ambos') %>% 
  filter(date <= '2026-12-01')

pim_transf <- split_series(pim_data, 'BRIND0002000OOML', type = 'realizado') %>% 
  snaive(nyears = NULL, end_forecast = '2026-12-01') %>% 
  drift(nyears = NULL)

pim_extrat <- split_series(pim_data, 'BRIND0003000OOML', type = 'realizado') %>% 
  snaive(nyears = NULL, end_forecast = '2026-12-01') %>% 
  drift(nyears = NULL)
```

```{r}
pim_topdown <- top_down(target_agg = pim_geral,
                        filter(pim_extrat, !forecast),
                        filter(pim_transf, !forecast))

colnames(b) <- c('date', 'forecast', pim_sids)
```


```{r}
ggplot(pim_topdown %>% 
         pivot_longer(-c(date, forecast)) %>% 
         filter(date>='2016-01-01'),
       aes(x = date, y = value, color = name)) +
  geom_line()
```

```{r}
pmc_sids <- c('BRIND0001000OOML', #Pim geral
              'BRRTL0030000OOML','BRRTL0023000OOML','BRRTL0024000OOML',
              'BRRTL0035000OOML','BRRTL0027000OOML','BRRTL0026000OOML',
              'BRRTL0034000OOML')

pmc_data <- load_clean_series(pmc_sids, auth_path)

pmc_topdown <- top_down(
  target_agg = split_series(pmc_data, 'BRIND0001000OOML', type = 'ambos') %>% 
    filter(date <= '2026-12-01'),
  split_series(pmc_data, 'BRRTL0030000OOML', type = 'realizado'),
  split_series(pmc_data, 'BRRTL0023000OOML', type = 'realizado'),
  split_series(pmc_data, 'BRRTL0024000OOML', type = 'realizado'),
  split_series(pmc_data, 'BRRTL0035000OOML', type = 'realizado'),
  split_series(pmc_data, 'BRRTL0027000OOML', type = 'realizado'),
  split_series(pmc_data, 'BRRTL0026000OOML', type = 'realizado'),
  split_series(pmc_data, 'BRRTL0034000OOML', type = 'realizado')
  )

colnames(pmc_topdown) <- c('date','forecast',pmc_sids)
```

##### PMC

```{r}
plot_pmc <- pmc_topdown %>% 
         pivot_longer(-c(date, forecast)) %>% 
         filter(date>='2016-01-01')

ggplot(plot_pmc,
       aes(x = date, y = value)) +
  geom_line() +
  facet_wrap(~name, scale = 'free_y') +
  annotate("rect",
         xmin = max(filter(plot_pmc,!forecast)$date),
         xmax = max(plot_pmc$date),
         ymin = min(filter(plot_pmc,!forecast)$value),
         ymax = Inf,
         alpha = 0.2)
```














#### Teste projeções naive

```{r}
lista_teste <- lista_4casthub_raw %>% 
  filter(status == 'teste') %>% 
  select(c(serie, nome_indicador))

lista_data <- load_clean_series(lista_teste$serie, auth_path)
end_forecast = '2026-01-01'

lista_forecast <- tibble()
for (sid in unique(lista_data$sid)) {
  sid_data <- split_series(lista_data, sid, type = 'realizado') %>% 
    mutate(forecast = F)
  
  #Detect gaps 
  periodicity_sid <- get_periodicity(sid_data)
  sid_gap <- sid_data %>% 
    mutate(month = format(date, '%m') %>% 
             as.numeric(),
           diff_months = month - lag(month, 1)) %>% 
    na.omit()
  
  if(any(sid_gap$diff_months > periodicity_sid$p_ngap)){
    warning(paste0("O sid ", sid, "possui buracos na série!"))
  } else {
    #ERRO drift_hist para o sid = 'BRLDG0034000OOML'
    sid_holt <- holtWinter(sid_data, end_forecast = end_forecast) %>% 
      rename(holtwinters = vl) %>% 
      filter(forecast) %>% 
      pivot_longer(-c(date, forecast))
    
    sid_arima <- arimaUnivariate(sid_data, end_forecast = end_forecast) %>% 
      rename(arima = vl) %>% 
      filter(forecast) %>% 
      pivot_longer(-c(date, forecast))
    
    sid_snaive_drift <- snaive(sid_data,
                               nyears = 1, 
                               end_forecast = end_forecast) %>% 
      drift() %>% 
      rename(snaive_drift = vl) %>% 
      filter(forecast) %>% 
      pivot_longer(-c(date, forecast))
    
    sid_seas_adj <- get_seas_adj(sid_data, type = 'STL') %>% 
      naive(end_forecast = end_forecast) %>% 
      drift()
    
    sid_seas_ratio <- seas_ratio(sid_data, sid_seas_adj, nyears = 5) %>% 
      rename(seas_ratio = vl) %>% 
      filter(forecast) %>% 
      pivot_longer(-c(date, forecast))
    
    sid_data <- sid_data  %>% 
      pivot_longer(-c(date, forecast))
    
    bind_forecasts <- sid_data %>% 
      bind_rows(sid_holt,
                sid_arima, 
                sid_snaive_drift,
                sid_seas_ratio) %>% 
      mutate(sid = sid)
    
    lista_forecast <- lista_forecast %>% 
      bind_rows(bind_forecasts)
  }
}

```



```{r}
ggplot(filter(lista_forecast, date >= '2016-01-01'),
       aes(x = date, y = value, color = name)) +
  geom_line() +
  facet_wrap(~sid, scale = 'free')
```





